# ================================
# Secret
# ================================
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-mvc-kotlin
type: Opaque
stringData:
  # ---------------------------------------------------
  application.properties: |-
    # Google Cloud
    gcp-project-id=ehealth-testing-1
    gcp-mongo-secret-name=mongo-atlas-uri-hl7-gateway
    
    # Spring stuff
    server.error.include-message=always
  # ---------------------------------------------------
  elasticapm.properties: |-
    service_name=spring-boot-mvc-kotlin
    application_packages=io.h4h.kotlinskeletonmvc.*
    server_urls=https://83fd6eb996c24a6fb376819480bd0324.apm.europe-west3.gcp.cloud.es.io:443
    secret_token=XXXXXXXXXXXXXXXXX
  # ---------------------------------------------------
  gcp-serviceaccount.json: |-
    {
      "type": "service_account"
    }


